'tabs.immeubles': 'Immeubles',
'tabs.societes': 'Sociétés',
'immeubles.addTitle': 'Ajouter un immeuble',
'immeubles.namePlaceholder': 'Ex: Immeuble A',
'immeubles.create': 'Créer',
'immeubles.creating': 'Création...',
'immeubles.listTitle': 'Liste des immeubles',
'immeubles.noResponsable': 'Aucun responsable assigné',
'immeubles.responsableIs': 'Responsable:',
'immeubles.inviteResponsable': 'Inviter',
'immeubles.inviteSuccess': 'Invitation envoyée',
'societes.inviteTitle': 'Inviter une société externe',
'societes.listTitle': 'Sociétés externes',
'societes.success': 'Invitation envoyée',
'residents.noImmeuble': 'Aucun immeuble',
